// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: readproto/read.proto

package readproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// import "google/protobuf/empty.proto";
type Blogr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authorid string `protobuf:"bytes,2,opt,name=authorid,proto3" json:"authorid,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Blogr) Reset() {
	*x = Blogr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readproto_read_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blogr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blogr) ProtoMessage() {}

func (x *Blogr) ProtoReflect() protoreflect.Message {
	mi := &file_readproto_read_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blogr.ProtoReflect.Descriptor instead.
func (*Blogr) Descriptor() ([]byte, []int) {
	return file_readproto_read_proto_rawDescGZIP(), []int{0}
}

func (x *Blogr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blogr) GetAuthorid() string {
	if x != nil {
		return x.Authorid
	}
	return ""
}

func (x *Blogr) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blogr) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Blogid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Blogid) Reset() {
	*x = Blogid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readproto_read_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blogid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blogid) ProtoMessage() {}

func (x *Blogid) ProtoReflect() protoreflect.Message {
	mi := &file_readproto_read_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blogid.ProtoReflect.Descriptor instead.
func (*Blogid) Descriptor() ([]byte, []int) {
	return file_readproto_read_proto_rawDescGZIP(), []int{1}
}

func (x *Blogid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_readproto_read_proto protoreflect.FileDescriptor

var file_readproto_read_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x61, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x63, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x67, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x18, 0x0a, 0x06, 0x42, 0x6c, 0x6f,
	0x67, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x32, 0x4b, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x6c,
	0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x52, 0x65, 0x61,
	0x64, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x69, 0x64, 0x1a, 0x13, 0x2e, 0x73, 0x65,
	0x70, 0x61, 0x72, 0x61, 0x74, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x72,
	0x42, 0x18, 0x5a, 0x16, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x65, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x72, 0x65, 0x61, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_readproto_read_proto_rawDescOnce sync.Once
	file_readproto_read_proto_rawDescData = file_readproto_read_proto_rawDesc
)

func file_readproto_read_proto_rawDescGZIP() []byte {
	file_readproto_read_proto_rawDescOnce.Do(func() {
		file_readproto_read_proto_rawDescData = protoimpl.X.CompressGZIP(file_readproto_read_proto_rawDescData)
	})
	return file_readproto_read_proto_rawDescData
}

var file_readproto_read_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_readproto_read_proto_goTypes = []interface{}{
	(*Blogr)(nil),  // 0: separategrpc.Blogr
	(*Blogid)(nil), // 1: separategrpc.Blogid
}
var file_readproto_read_proto_depIdxs = []int32{
	1, // 0: separategrpc.ReadAllBlogService.ReadBlog:input_type -> separategrpc.Blogid
	0, // 1: separategrpc.ReadAllBlogService.ReadBlog:output_type -> separategrpc.Blogr
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_readproto_read_proto_init() }
func file_readproto_read_proto_init() {
	if File_readproto_read_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_readproto_read_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blogr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_readproto_read_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blogid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_readproto_read_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_readproto_read_proto_goTypes,
		DependencyIndexes: file_readproto_read_proto_depIdxs,
		MessageInfos:      file_readproto_read_proto_msgTypes,
	}.Build()
	File_readproto_read_proto = out.File
	file_readproto_read_proto_rawDesc = nil
	file_readproto_read_proto_goTypes = nil
	file_readproto_read_proto_depIdxs = nil
}
